### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by qzha130** [bluesurfer/pyforest#2]
OS: Windows 64 Bit
Pip: 19.2.2

PS P:\> pip install --user pyforest
Collecting pyforest
  Downloading https://files.pythonhosted.org/packages/ca/7a/2280448ba4202604eb3f9e23d9a4fd0ca1473d31aca0a90fdb5f31dd902c/pyforest-0.1.1.tar.gz (3.4MB)
     |████████████████████████████████| 3.4MB 2.2MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zhaoq\\AppData\\Local\\Temp\\pip-install-bdpcqvws\\pyforest\\setup.py'"'"'; __file__='"'"'C:\\Users\\zhaoq\\AppData\\Local\\Temp\\pip-install-bdpcqvws\\pyforest\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\zhaoq\AppData\Local\Temp\pip-install-bdpcqvws\pyforest\
    Complete output (25 lines):
    Download error on https://pypi.org/simple/pyscaffold/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
    Couldn't find index page for 'pyscaffold' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
    No local packages or working download links found for pyscaffold<3.3a0,>=3.2a0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zhaoq\AppData\Local\Temp\pip-install-bdpcqvws\pyforest\setup.py", line 20, in <module>
        setup(use_pyscaffold=True)
      File "c:\program files\python37\lib\site-packages\setuptools\__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "c:\program files\python37\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\program files\python37\lib\site-packages\setuptools\dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 1075, in obtain
        return installer(requirement)
      File "c:\program files\python37\lib\site-packages\setuptools\dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\program files\python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyscaffold<3.3a0,>=3.2a0')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by qzha130** [comment]
Solved ! After install pyscaffold
